(cl:in-package strategy-msg)
(cl:export '(DY-VAL
          DY
          DX-VAL
          DX
          RD-VAL
          RD
          LD-VAL
          LD
          WR-VAL
          WR
          WL-VAL
          WL
          SLOPE_AVG-VAL
          SLOPE_AVG
          LEFTBLUEOBS_XMAX-VAL
          LEFTBLUEOBS_XMAX
          RIGHTBLUEOBS_XMIN-VAL
          RIGHTBLUEOBS_XMIN
          IN_REDDOOR_FLAG-VAL
          IN_REDDOOR_FLAG
          L_XMAX-VAL
          L_XMAX
          R_XMIN-VAL
          R_XMIN
          B_OBS_FLAG-VAL
          B_OBS_FLAG
          Y_OBS_FLAG-VAL
          Y_OBS_FLAG
          L_CENTER_DY-VAL
          L_CENTER_DY
          R_CENTER_DY-VAL
          R_CENTER_DY
          CENTER_DY-VAL
          CENTER_DY
          ONE_B_FLAG-VAL
          ONE_B_FLAG
          TWO_B_FLAG-VAL
          TWO_B_FLAG
          DEEP_SUM-VAL
          DEEP_SUM
))