(cl:defpackage tku_msgs-srv
  (:use )
  (:export
   "CHECKSECTOR"
   "<CHECKSECTOR-REQUEST>"
   "CHECKSECTOR-REQUEST"
   "<CHECKSECTOR-RESPONSE>"
   "CHECKSECTOR-RESPONSE"
   "READMOTION"
   "<READMOTION-REQUEST>"
   "READMOTION-REQUEST"
   "<READMOTION-RESPONSE>"
   "READMOTION-RESPONSE"
   "SENDHANDSPEED"
   "<SENDHANDSPEED-REQUEST>"
   "SENDHANDSPEED-REQUEST"
   "<SENDHANDSPEED-RESPONSE>"
   "SENDHANDSPEED-RESPONSE"
  ))

